import * as T from './three.module.js';
import {fresh,step,FLOOR,CEILING} from './physics.mjs';
import {createLidarTracer} from './lidar-ray.mjs';
const $=s=>document.querySelector(s), canvas=$('#scene');
let renderer;try{renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});}catch(e){$('#intro').hidden=true;$('#error').hidden=false;throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.65));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;
const scene=new T.Scene();scene.background=new T.Color('#060d13');scene.fog=new T.FogExp2('#080f15',.038);
const camera=new T.PerspectiveCamera(40,innerWidth/innerHeight,.1,110);camera.position.set(0,1.1,23.6);camera.lookAt(0,0,0);
const world=new T.Group();scene.add(world);
let time=0,mode='intro',state=fresh(),held=false,tapUntil=0,paused=false,shake=0,worldOffset=0,heroBlend=1,lastTime=0,muted=false;
let aspect=innerWidth/innerHeight;const droneX=()=>aspect<.8?-2.5:-5.5;
let seed=43;function rnd(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}const rand=(a,b)=>a+rnd()*(b-a);
function noise(x,y,z=0){return Math.sin(x*1.37+y*.83+z*.45)*.45+Math.sin(x*3.18-y*2.12+z)*.23+Math.cos(x*6.73+y*4.97-z*1.7)*.12+Math.sin(x*15.4-y*9.6+z)*.07;}
const rockMat=new T.MeshStandardMaterial({color:0x58646a,roughness:.87,metalness:.12,vertexColors:true});
// Triplanar mineral grain, sediment striations and damp specular patches.
rockMat.onBeforeCompile=shader=>{shader.vertexShader='varying vec3 vRockPosition;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\nvRockPosition = position;');shader.fragmentShader='varying vec3 vRockPosition;\nfloat hash3(vec3 p){return fract(sin(dot(p,vec3(127.1,311.7,74.7)))*43758.5453);}\nfloat rockNoise(vec3 p){vec3 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(mix(hash3(i),hash3(i+vec3(1,0,0)),f.x),mix(hash3(i+vec3(0,1,0)),hash3(i+vec3(1,1,0)),f.x),f.y),mix(mix(hash3(i+vec3(0,0,1)),hash3(i+vec3(1,0,1)),f.x),mix(hash3(i+vec3(0,1,1)),hash3(i+vec3(1,1,1)),f.x),f.y),f.z);}\n'+shader.fragmentShader;shader.fragmentShader=shader.fragmentShader.replace('#include <color_fragment>',`#include <color_fragment>
float n=rockNoise(vRockPosition*5.0)*.5+rockNoise(vRockPosition*18.0)*.3+rockNoise(vRockPosition*67.)*.2;
float strata=sin(vRockPosition.y*26.+rockNoise(vRockPosition*2.)*8.)*.08;
diffuseColor.rgb*=.5+n*.75+strata;
diffuseColor.rgb=mix(diffuseColor.rgb,diffuseColor.rgb*vec3(1.22,1.08,.86),smoothstep(.52,.75,n)*.5);`);shader.fragmentShader=shader.fragmentShader.replace('#include <roughnessmap_fragment>','#include <roughnessmap_fragment>\nroughnessFactor = clamp(.5 + rockNoise(vRockPosition*3.)*.42,.4,.95);');};
const metal=new T.MeshStandardMaterial({color:0x27353b,metalness:.88,roughness:.38});const darkMetal=new T.MeshStandardMaterial({color:0x111b21,metalness:.76,roughness:.43});const rust=new T.MeshStandardMaterial({color:0x44362c,metalness:.7,roughness:.72});const red=new T.MeshStandardMaterial({color:0x983326,metalness:.5,roughness:.45});const black=new T.MeshStandardMaterial({color:0x121b22,metalness:.55,roughness:.42});
function mesh(geo,mat,parent=world,x=0,y=0,z=0){let m=new T.Mesh(geo,mat);m.position.set(x,y,z);parent.add(m);return m;}
function bar(a,b,r,mat,parent){const av=new T.Vector3(...a),bv=new T.Vector3(...b);let m=mesh(new T.CylinderGeometry(r,r,av.distanceTo(bv),7),mat,parent);m.position.copy(av.add(bv).multiplyScalar(.5));m.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),new T.Vector3(...b).sub(new T.Vector3(...a)).normalize());return m;}
function tube(points,r,mat,parent){return mesh(new T.TubeGeometry(new T.CatmullRomCurve3(points.map(p=>new T.Vector3(...p))),Math.max(24,points.length*8),r,6,false),mat,parent);}
function stoneGeo(radius=1,detail=1){let g=new T.IcosahedronGeometry(radius,detail);const p=g.attributes.position,colors=[];for(let i=0;i<p.count;i++){const x=p.getX(i),y=p.getY(i),z=p.getZ(i),k=1+noise(x*2.3,y*2.3,z*2.3)*.2;p.setXYZ(i,x*k,y*k,z*k);let c=.62+noise(x*3,y*3,z*3)*.28;colors.push(c,c*.98,c*.96);}g.setAttribute('color',new T.Float32BufferAttribute(colors,3));g.computeVertexNormals();return g;}
const stone=stoneGeo(1,1);
function makeSurface(x0,length,side){const g=new T.PlaneGeometry(length,10,Math.round(length*3),30),p=g.attributes.position,colors=[];for(let i=0;i<p.count;i++){let x=p.getX(i)+x0,y=p.getY(i),z;if(side==='back'){z=-5.4+noise(x*.65,y*.7)*1.5+noise(x*2,y*2)*.28;p.setXYZ(i,x,y*1.35,z);}else{z=y-1.5;let yy=(side==='floor'?-5.8:5.8)+(side==='floor'?-1:1)*Math.abs(noise(x*.8,z*.7))*.9;p.setXYZ(i,x,yy,z);}let c=.65+noise(x*.8,y*.9)*.32;colors.push(c,c,c);}g.setAttribute('color',new T.Float32BufferAttribute(colors,3));g.computeVertexNormals();let m=mesh(g,rockMat);m.material.side=T.DoubleSide;m.receiveShadow=true;return m;}
const scanRocks=[];const chunks=[];const chunkLength=22;for(let k=0;k<5;k++){let group=new T.Group();world.add(group);let start=k*chunkLength-33;for(const side of ['back','floor','ceiling']){let m=makeSurface(0,chunkLength,side);group.add(m);}group.position.x=start;for(let j=0;j<17;j++){const x=rand(-11,11),upper=rnd()>.5;let r=mesh(stone,rockMat,group,x,upper?6:-6,rand(-3,2));r.scale.set(rand(.6,2.3),rand(.25,.9),rand(.5,1.5));r.rotation.set(rnd()*2,rnd()*3,rnd()*2);r.receiveShadow=true;scanRocks.push(r);}chunks.push(group);}
// Repeating abandoned mine infrastructure behind the flight corridor.
const structures=[];for(let k=0;k<8;k++){const g=new T.Group();world.add(g);g.position.x=k*12-36;for(const z of [-4.3,-2.9]){bar([0,-5.5,z],[0,4.2,z],.105,rust,g);bar([0,4.2,z],[0,5.5,z-.3],.11,rust,g);}for(let y=-4;y<4.5;y+=1.4){bar([0,y,-4.3],[0,y,-2.9],.055,metal,g);mesh(new T.BoxGeometry(.28,.36,.1),metal,g,0,y,-2.83);}for(let y of [-3.9,-3.5])bar([-6,y,-3.1],[6,y,-3.1],.075,rust,g);tube([[-6,4.1,-3.7],[-2,3.6,-3.7],[2,3.5,-3.7],[6,4.1,-3.7]],.022,darkMetal,g);const lampMat=new T.MeshBasicMaterial({color:0xff9e46});mesh(new T.BoxGeometry(.14,.33,.18),lampMat,g,0,3.65,-2.73);let l=new T.PointLight(0xe98c40,3.8,6,2);l.position.set(.3,3.65,-2.4);g.add(l);structures.push(g);}
// Rails, flooded ledges and ballast.
const groundDecor=new T.Group();world.add(groundDecor);
for(let z of [-1.7,-.8])bar([-65,-5.36,z],[80,-5.36,z],.045,metal,groundDecor);
const wet=new T.MeshStandardMaterial({color:0x14232c,metalness:.9,roughness:.17,transparent:true,opacity:.65});for(let i=0;i<20;i++){let m=mesh(new T.CircleGeometry(rand(.5,1.7),24),wet,groundDecor,rand(-40,60),-5.48,rand(-2,2));m.rotation.x=-Math.PI/2;m.scale.x=2.8;}
const gravel=new T.InstancedMesh(stone,rockMat,480);const dummy=new T.Object3D();for(let i=0;i<480;i++){dummy.position.set(rand(-50,70),-5.55,rand(-3.4,3));dummy.scale.set(rand(.05,.25),rand(.05,.17),rand(.05,.23));dummy.rotation.set(rnd()*3,rnd()*3,rnd()*3);dummy.updateMatrix();gravel.setMatrixAt(i,dummy.matrix);}groundDecor.add(gravel);
// Protected industrial drone: four protected rotors inside a wide exoskeleton.
const drone=new T.Group();scene.add(drone);const rotors=[];
mesh(new T.BoxGeometry(.68,.35,.62),black,drone,0,0,0).castShadow=true;mesh(new T.BoxGeometry(.47,.16,.5),metal,drone,0,.21,-.03);mesh(new T.BoxGeometry(.57,.16,.39),black,drone,.05,-.23,.04);
for(let x of [-.66,.66])for(let z of [-.56,.56]){bar([0,.03,0],[x,.01,z],.05,black,drone);mesh(new T.CylinderGeometry(.10,.09,.2,12),metal,drone,x,.04,z);const ring=mesh(new T.TorusGeometry(.46,.04,7,48),darkMetal,drone,x,.03,z);ring.rotation.x=Math.PI/2;const prop=new T.Group();prop.position.set(x,.16,z);drone.add(prop);mesh(new T.BoxGeometry(.77,.017,.045),metal,prop);mesh(new T.BoxGeometry(.045,.017,.77),metal,prop);let disc=mesh(new T.CircleGeometry(.39,30),new T.MeshBasicMaterial({color:0xb7cbd0,transparent:true,opacity:.07,side:T.DoubleSide,depthWrite:false}),prop);disc.rotation.x=-Math.PI/2;rotors.push(prop);}
for(let y of [-.12,.16]){const points=[];for(let j=0;j<=64;j++){let a=j/64*Math.PI*2;points.push([Math.cos(a)*1.23,y,Math.sin(a)*1.02]);}tube(points,.022,metal,drone);}
for(let j=0;j<20;j++){let a=j/20*Math.PI*2;bar([Math.cos(a)*1.23,-.12,Math.sin(a)*1.02],[Math.cos(a)*1.23,.16,Math.sin(a)*1.02],.018,j%3===0?red:darkMetal,drone);}
for(let a of [0,Math.PI/3,Math.PI*2/3]){let pts=[];for(let j=0;j<=24;j++){let t=j/24*Math.PI;pts.push([Math.cos(t)*1.24*Math.cos(a),Math.sin(t)*.55-.05,Math.cos(t)*1.03*Math.sin(a)]);}tube(pts,.012,metal,drone);}
for(let z of [-.68,.68]){mesh(new T.BoxGeometry(.14,.2,.42),black,drone,1.06,.1,z);for(let j=-1;j<=1;j++){let led=mesh(new T.CylinderGeometry(.048,.048,.025,12),new T.MeshBasicMaterial({color:0xfff3bc}),drone,1.15,.09,z+j*.113);led.rotation.z=Math.PI/2;}mesh(new T.BoxGeometry(.035,.04,.37),new T.MeshBasicMaterial({color:0xddf8ff}),drone,1.15,.21,z);}
let camBody=mesh(new T.CylinderGeometry(.1,.1,.14,16),black,drone,.39,-.13,.05);camBody.rotation.z=Math.PI/2;let lens=mesh(new T.CylinderGeometry(.065,.065,.016,16),new T.MeshStandardMaterial({color:0x31556a,metalness:.95,roughness:.08}),drone,.47,-.13,.05);lens.rotation.z=Math.PI/2;
mesh(new T.SphereGeometry(.035,8,6),new T.MeshBasicMaterial({color:0x49b9ff}),drone,-.4,.14,.31);mesh(new T.SphereGeometry(.027,8,6),new T.MeshBasicMaterial({color:0xff4c27}),drone,-.8,.12,.6);
const spot=new T.SpotLight(0xffe2a4,240,34,.72,.65,.85);spot.position.set(1.2,.2,.2);spot.target.position.set(15,0,-3.4);drone.add(spot,spot.target);spot.castShadow=true;spot.shadow.mapSize.set(1024,1024);spot.shadow.bias=-.001;spot.shadow.normalBias=.05;
const halo=new T.PointLight(0xffdfab,18,12,1.35);halo.position.set(.7,.7,1.7);drone.add(halo);const rim=new T.DirectionalLight(0x9db6c9,1.4);rim.position.set(-5,8,5);scene.add(rim);scene.add(new T.HemisphereLight(0x586d7b,0x292017,.75));
// Warm reflected headlight keeps near obstacles readable without flattening the cave.
const bounce=new T.PointLight(0xffdfa8,28,18,1.15);bounce.position.set(4,.1,-.6);drone.add(bounce);
const navGlowTexture=(()=>{const c=document.createElement('canvas');c.width=c.height=64;const ctx=c.getContext('2d'),g=ctx.createRadialGradient(32,32,0,32,32,32);g.addColorStop(0,'rgba(255,255,255,1)');g.addColorStop(.12,'rgba(255,255,255,.9)');g.addColorStop(.35,'rgba(255,255,255,.25)');g.addColorStop(1,'rgba(255,255,255,0)');ctx.fillStyle=g;ctx.fillRect(0,0,64,64);return new T.CanvasTexture(c);})();
const navLights=[];
for(const [x,y,z,color] of [[-1.1,.17,.35,0xff593c],[-1.1,.17,-.35,0xff593c],[.6,.19,.86,0x58ffbe],[.6,.19,-.86,0x58ffbe],[0,.57,0,0xffc466],[0,-.28,0,0x75eaff]]){mesh(new T.SphereGeometry(.043,10,8),new T.MeshBasicMaterial({color}),drone,x,y,z);const glow=new T.Sprite(new T.SpriteMaterial({map:navGlowTexture,color,transparent:true,depthWrite:false,blending:T.AdditiveBlending,opacity:.8}));glow.position.set(x,y,z);glow.scale.setScalar(.36);drone.add(glow);navLights.push(glow);}
// Soft-edged volume in the headlight, additive and depth-aware.
const beamMat=new T.ShaderMaterial({transparent:true,depthWrite:false,blending:T.AdditiveBlending,side:T.DoubleSide,uniforms:{opacity:{value:.10}},vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec2 vUv;uniform float opacity;void main(){float edge=pow(sin(vUv.y*3.14159),1.6);float len=pow(1.-vUv.x,1.7)*smoothstep(0.,.07,vUv.x);gl_FragColor=vec4(1.,.84,.53,edge*len*opacity);}'});
const beamGeo=new T.BufferGeometry();beamGeo.setAttribute('position',new T.Float32BufferAttribute([1.1,.1,0,19,15,-1,19,-15,-1,1.1,.1,0,19,-15,-1,1.1,.09,0],3));beamGeo.setAttribute('uv',new T.Float32BufferAttribute([0,.5,1,1,1,0,0,.5,1,0,0,.5],2));mesh(beamGeo,beamMat,drone);
const dustCount=650,dustPos=new Float32Array(dustCount*3);for(let i=0;i<dustCount;i++){dustPos[i*3]=rand(-24,25);dustPos[i*3+1]=rand(-5.2,5.5);dustPos[i*3+2]=rand(-3,6);}const dustG=new T.BufferGeometry();dustG.setAttribute('position',new T.BufferAttribute(dustPos,3));const dustM=new T.ShaderMaterial({transparent:true,depthWrite:false,blending:T.AdditiveBlending,uniforms:{dronePos:{value:new T.Vector3()},clock:{value:0}},vertexShader:`uniform vec3 dronePos;uniform float clock;varying float alpha;void main(){vec3 p=position;p.y+=sin(clock*.3+p.x)*.07;vec3 delta=p-dronePos;float beam=step(0.,delta.x)*exp(-abs(delta.y)/max(.3,delta.x*.65))*exp(-delta.x*.17);alpha=.06+beam*.7;vec4 mv=modelViewMatrix*vec4(p,1.);gl_PointSize=clamp(32./-mv.z,1.,3.);gl_Position=projectionMatrix*mv;}`,fragmentShader:'varying float alpha;void main(){float d=length(gl_PointCoord-.5);gl_FragColor=vec4(.95,.87,.67,alpha*smoothstep(.5,.1,d));}'});const dust=new T.Points(dustG,dustM);scene.add(dust);
const obstacles=[];let nextObstacle=16,lastTallX=-100;
function crystal(height,width,top){const rootDepth=1.7,fullHeight=height+rootDepth;const g=new T.CylinderGeometry(.035,width,fullHeight,9,9);let p=g.attributes.position,cs=[];for(let i=0;i<p.count;i++){let x=p.getX(i),y=p.getY(i),z=p.getZ(i);const along=fullHeight/2-y,original=along/fullHeight,shape=Math.min(1,along/height);if(original>.0001){x*=shape/original;z*=shape/original;}const k=1+noise(x*8,y*4,z*7)*.17;p.setXYZ(i,x*k,y,z*k);let c=.62+noise(x*4,y*3,z*4)*.25;cs.push(c,c,c);}g.setAttribute('color',new T.Float32BufferAttribute(cs,3));g.computeVertexNormals();let m=new T.Mesh(g,rockMat);m.position.y=top?CEILING+(rootDepth-height)/2:FLOOR+(height-rootDepth)/2;if(top)m.rotation.z=Math.PI;m.castShadow=true;m.receiveShadow=true;return m;}
// Solid, softly lit membranes keep their silhouette throughout the wing beat.
const batFur=new T.MeshStandardMaterial({color:0x42382f,roughness:1,metalness:0,emissive:0x211b17,emissiveIntensity:.22});
const batMembrane=new T.MeshStandardMaterial({color:0x594138,roughness:1,metalness:0,side:T.DoubleSide,emissive:0x35231e,emissiveIntensity:.22});
const batBone=new T.MeshStandardMaterial({color:0x695244,roughness:1});
function bat(){const g=new T.Group();const body=mesh(new T.SphereGeometry(.15,16,12),batFur,g,0,-.015,.04);body.scale.set(.73,1.65,.8);mesh(new T.SphereGeometry(.12,16,12),batFur,g,0,.205,.055);const muzzle=mesh(new T.SphereGeometry(.065,12,8),batFur,g,0,.18,.15);muzzle.scale.set(1,.65,.65);
for(const side of [-1,1]){const ear=mesh(new T.ConeGeometry(.065,.20,12),batFur,g,side*.082,.35,.03);ear.rotation.z=-side*.2;ear.scale.z=.45;mesh(new T.SphereGeometry(.014,8,6),black,g,side*.062,.228,.153);}
const wings=[];for(const side of [-1,1]){const w=new T.Group();w.position.set(side*.075,.05,0);w.scale.x=side;w.userData.side=side;g.add(w);const s=new T.Shape();s.moveTo(0,.02);s.quadraticCurveTo(.16,.23,.34,.26);s.quadraticCurveTo(.52,.27,.86,.13);s.quadraticCurveTo(.65,.02,.64,-.16);s.quadraticCurveTo(.47,-.045,.40,-.26);s.quadraticCurveTo(.25,-.10,.19,-.30);s.quadraticCurveTo(.07,-.15,0,-.18);s.closePath();const geo=new T.ExtrudeGeometry(s,{depth:.019,steps:1,bevelEnabled:true,bevelSize:.008,bevelThickness:.008,bevelSegments:2,curveSegments:16});const membrane=mesh(geo,batMembrane,w);membrane.position.z=-.01;
for(const end of [[.86,.13],[.64,-.16],[.40,-.26],[.19,-.30]])tube([[0,.02,.023],[.30,.21,.036],[end[0],end[1],.018]],.008,batBone,w);tube([[0,.02,.025],[.16,.21,.028],[.34,.26,.029],[.63,.21,.025],[.86,.13,.019]],.012,batBone,w);wings.push(w);}
const tail=mesh(new T.ConeGeometry(.09,.2,3),batMembrane,g,0,-.28,0);tail.rotation.z=Math.PI;tail.scale.z=.35;g.rotation.x=.12;g.userData.wings=wings;return g;}
function addObstacle(){const top=rnd()>.5,kind=nextObstacle>30&&rnd()<.25?'bat':'rock',baseHeight=rand(1.8,3.4),tall=kind==='rock'&&nextObstacle-lastTallX>28&&rnd()<.13,height=tall?rand(3.7,4.25):baseHeight,width=rand(.65,1.15);if(tall)lastTallX=nextObstacle;const g=new T.Group();world.add(g);let o={x:nextObstacle,y:rand(-2.5,2.5),baseY:0,phase:rnd()*6,kind,top,height,width,hit:false,group:g};o.baseY=o.y;if(kind==='rock'){g.add(crystal(height,width,top));for(let j of [-1,1]){let m=crystal(height*rand(.28,.48),width*.53,top);m.position.x=j*width*.9;m.position.z=-.55;g.add(m);}}else{g.add(bat());}g.position.set(o.x+droneX(),kind==='bat'?o.y:0,0);obstacles.push(o);nextObstacle+=rand(8,12);}
function disposeObject(g){g.traverse(n=>{if(n.geometry)n.geometry.dispose();});world.remove(g);}
// Two thin lidar fans: depth rows, radial rays and moving cross-lines.
const lidar=new T.Group();scene.add(lidar);
const lidarPositions=new Float32Array(2400),lidarGeometry=new T.BufferGeometry();lidarGeometry.setAttribute('position',new T.BufferAttribute(lidarPositions,3).setUsage(T.DynamicDrawUsage));
const lidarMaterial=new T.LineBasicMaterial({color:0x4ae971,toneMapped:false,transparent:true,opacity:.29,blending:T.AdditiveBlending,depthWrite:false});
const lidarGrid=new T.LineSegments(lidarGeometry,lidarMaterial);lidarGrid.frustumCulled=false;lidar.add(lidarGrid);
const lidarSweepPositions=new Float32Array(240),lidarSweepGeometry=new T.BufferGeometry();lidarSweepGeometry.setAttribute('position',new T.BufferAttribute(lidarSweepPositions,3).setUsage(T.DynamicDrawUsage));
const lidarSweep=new T.LineSegments(lidarSweepGeometry,new T.LineBasicMaterial({color:0x86ff9b,toneMapped:false,transparent:true,opacity:.7,blending:T.AdditiveBlending,depthWrite:false}));lidarSweep.frustumCulled=false;lidar.add(lidarSweep);
const traceLidar=createLidarTracer(),scanOrigin=new T.Vector3(),scanTarget=new T.Vector3(),scanCenter=new T.Vector3();
function updateLidar(){const on=mode==='intro'||state.mode==='playing';lidar.visible=on;if(!on)return;let n=0,k=0;const source=drone.position,scale=mode==='intro'?1.4:1;
// Refresh moving chunk transforms before casting; cache each fan ray for all cross-lines.
world.updateMatrixWorld(true);
const nearbyRocks=scanRocks.filter(rock=>Math.abs(rock.getWorldPosition(scanCenter).x-source.x)<9*scale);
for(const o of obstacles)if(o.kind==='rock'&&Math.abs(o.x+droneX()-worldOffset-source.x)<9*scale)nearbyRocks.push(...o.group.children);
const endpoints=new Map();
function endpoint(dir,u,z){const key=dir+':'+u.toFixed(4)+':'+z;if(endpoints.has(key))return endpoints.get(key);scanOrigin.set(source.x,source.y+dir*.3,source.z);scanTarget.set(source.x+u*3.3*scale,dir>0?5.7:-5.7,source.z+z);const hit=traceLidar(scanOrigin,scanTarget,nearbyRocks);endpoints.set(key,hit);return hit;}
function point(dir,u,t,z){const e=endpoint(dir,u,z),sy=source.y+dir*.3;return [source.x+(e.x-source.x)*t,sy+(e.y-sy)*t,source.z+(e.z-source.z)*t];}
function line(a,b,sweep=false){const target=sweep?lidarSweepPositions:lidarPositions;let i=sweep?k:n;for(const p of [a,b])for(const value of p)target[i++]=value;if(sweep)k=i;else n=i;}
for(const dir of [-1,1]){for(const z of [-.85,.7]){for(let j=0;j<=10;j++){const u=j/5-1;line(point(dir,u,.03,z),point(dir,u,1,z));}for(let j=1;j<=7;j++){let t=j/7;for(let a=0;a<10;a++)line(point(dir,a/5-1,t,z),point(dir,(a+1)/5-1,t,z));}const scan=.06+(time*.38%1)*.94;for(let a=0;a<10;a++)line(point(dir,a/5-1,scan,z),point(dir,(a+1)/5-1,scan,z),true);}for(let a=-1;a<=1;a+=.5)line(point(dir,a,1,-.85),point(dir,a,1,.7));}
lidarGeometry.setDrawRange(0,n/3);lidarSweepGeometry.setDrawRange(0,k/3);lidarGeometry.attributes.position.needsUpdate=true;lidarSweepGeometry.attributes.position.needsUpdate=true;lidarMaterial.opacity=.28+Math.sin(time*2)*.025;}
// Sparks and smoke keep simulating during the final crash.
const particles=[];const puffTexture=(()=>{let c=document.createElement('canvas');c.width=c.height=64;let x=c.getContext('2d'),gr=x.createRadialGradient(32,32,0,32,32,32);gr.addColorStop(0,'rgba(220,228,230,.7)');gr.addColorStop(.3,'rgba(166,180,190,.35)');gr.addColorStop(1,'rgba(120,140,160,0)');x.fillStyle=gr;x.fillRect(0,0,64,64);return new T.CanvasTexture(c);})();
function emit(smoke=false){for(let i=0;i<(smoke?2:25);i++){let mat=new T.SpriteMaterial({map:puffTexture,color:smoke?0x82939b:0xffa544,transparent:true,depthWrite:false,blending:smoke?T.NormalBlending:T.AdditiveBlending});let m=new T.Sprite(mat);m.position.copy(drone.position);m.position.z+=.5;let size=smoke?rand(.35,.7):rand(.05,.12);m.scale.setScalar(size);scene.add(m);particles.push({m,vx:rand(-2,2)*(smoke?.15:1),vy:smoke?rand(.5,1.3):rand(-3,3),age:0,life:smoke?rand(1.4,2.4):rand(.3,.7),smoke,size});}}
// Four slightly detuned blade tones, broadband airflow and the higher electric motor whine.
let audio;function initAudio(){if(audio){audio.ctx.resume();return;}try{const ctx=new AudioContext(),master=ctx.createGain(),gain=ctx.createGain(),highpass=ctx.createBiquadFilter(),filter=ctx.createBiquadFilter();master.gain.value=muted?0:.26;master.connect(ctx.destination);highpass.type='highpass';highpass.frequency.value=145;filter.type='lowpass';filter.frequency.value=3400;gain.gain.value=.3;gain.connect(highpass);highpass.connect(filter);filter.connect(master);
const real=new Float32Array(9),imag=new Float32Array([0,1,.38,.23,.12,.08,.04,.025,.01]),wave=ctx.createPeriodicWave(real,imag),motors=[];
for(let i=0;i<4;i++){const blade=ctx.createOscillator(),level=ctx.createGain(),whine=ctx.createOscillator(),whineLevel=ctx.createGain();blade.setPeriodicWave(wave);blade.frequency.value=195+i*3.7;level.gain.value=.16;blade.connect(level);level.connect(gain);whine.type='sine';whine.frequency.value=1100+i*17;whineLevel.gain.value=.021;whine.connect(whineLevel);whineLevel.connect(gain);blade.start();whine.start();motors.push({blade,whine});}
const buffer=ctx.createBuffer(1,ctx.sampleRate*3,ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=Math.random()*2-1;const wind=ctx.createBufferSource(),airFilter=ctx.createBiquadFilter(),airGain=ctx.createGain(),pulse=ctx.createOscillator(),pulseDepth=ctx.createGain();wind.buffer=buffer;wind.loop=true;airFilter.type='bandpass';airFilter.frequency.value=1550;airFilter.Q.value=.6;airGain.gain.value=.22;pulse.type='sine';pulse.frequency.value=98;pulseDepth.gain.value=.055;pulse.connect(pulseDepth);pulseDepth.connect(airGain.gain);wind.connect(airFilter);airFilter.connect(airGain);airGain.connect(gain);wind.start();pulse.start();audio={ctx,master,gain,filter,motors,airFilter,airGain,pulse};}catch(e){}}
function impactSound(){if(!audio)return;const {ctx,master}=audio,buf=ctx.createBuffer(1,ctx.sampleRate*.2,ctx.sampleRate),data=buf.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*Math.exp(-i/data.length*7);const src=ctx.createBufferSource(),f=ctx.createBiquadFilter(),g=ctx.createGain();src.buffer=buf;f.type='lowpass';f.frequency.value=1700;g.gain.value=.5;src.connect(f);f.connect(g);g.connect(master);src.start();}
function updateHUD(){ $('#distance').textContent=String(Math.floor(state.distance)).padStart(4,'0');$('#lives').setAttribute('aria-label',`${state.lives} жизни`);[...$('#lives').children].forEach((e,i)=>e.classList.toggle('lost',i>=state.lives));}
function start(){for(const o of obstacles)disposeObject(o.group);obstacles.length=0;nextObstacle=16;lastTallX=-100;seed=(Math.random()*4294967296)>>>0;state=fresh();mode='playing';held=false;tapUntil=0;paused=false;heroBlend=0;worldOffset=0;$('#intro').hidden=true;$('#end').hidden=true;$('#paused').hidden=true;$('#hud').hidden=false;$('#start').blur();$('#restart').blur();initAudio();updateHUD();}
function pause(){if(mode!=='playing'||state.mode!=='playing')return;paused=!paused;held=false;tapUntil=0;$('#paused').hidden=!paused;if(audio)audio.gain.gain.setTargetAtTime(paused?0:.3,audio.ctx.currentTime,.1);if(paused)$('#resume').focus();}
$('#start').onclick=start;$('#restart').onclick=start;$('#pause').onclick=pause;$('#resume').onclick=pause;$('#sound').onclick=()=>{muted=!muted;if(audio)audio.master.gain.value=muted?0:.26;$('#sound').textContent=muted?'×':'♪';$('#sound').setAttribute('aria-label',muted?'Включить звук':'Выключить звук');};
window.addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();if(mode==='playing'&&!paused){held=true;tapUntil=time+.16;}}if(e.code==='Escape'&&!e.repeat)pause();});window.addEventListener('keyup',e=>{if(e.code==='Space'){e.preventDefault();held=false;}});canvas.addEventListener('pointerdown',e=>{if(mode==='playing'&&!paused){held=true;tapUntil=time+.18;canvas.setPointerCapture(e.pointerId);}});window.addEventListener('pointerup',()=>held=false);window.addEventListener('pointercancel',()=>{held=false;tapUntil=0;});window.addEventListener('blur',()=>{held=false;if(mode==='playing'&&!paused)pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode==='playing'&&!paused)pause();});
// The decorative vignette must never consume flight input.
$('#game').addEventListener('pointerdown',e=>{if(e.target===canvas)return;if(e.target.closest('button')||e.target.closest('.screen'))return;if(mode==='playing'&&!paused){held=true;tapUntil=time+.18;}});
function resize(){aspect=innerWidth/innerHeight;camera.aspect=aspect;camera.position.z=aspect<.8?30:23.6;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);}window.addEventListener('resize',resize);resize();
function animate(ms){requestAnimationFrame(animate);let dt=Math.min((ms-lastTime)/1000,.035);lastTime=ms;if(!dt)return;if(paused){renderer.render(scene,camera);return;}time+=dt;
if(mode==='playing'){while(nextObstacle<state.distance+55)addObstacle();for(const o of obstacles)if(o.kind==='bat')o.y=o.baseY+Math.sin(time*2+o.phase)*.8;const hit=step(state,dt,held||time<tapUntil,obstacles);if(hit){shake=.25;emit();impactSound();updateHUD();$('#impact').style.opacity='.8';setTimeout(()=>$('#impact').style.opacity='0',120);}worldOffset=state.distance;updateHUD();if(state.mode==='over'&&$('#end').hidden){$('#score').textContent=Math.floor(state.distance);$('#end').hidden=false;$('#hud').hidden=true;$('#end').focus({preventScroll:true});}if(state.mode==='crashing'||state.mode==='over'){if(rnd()<dt*20)emit(true);spot.intensity=T.MathUtils.lerp(spot.intensity,state.landed?1:16,dt*3);beamMat.uniforms.opacity.value=state.landed?.008:.04;}}
else worldOffset=time*.32;
world.position.x=-worldOffset;groundDecor.position.x=Math.floor(worldOffset/60)*60;
for(let i=0;i<chunks.length;i++){const base=i*chunkLength-33;chunks[i].position.x=base+Math.floor((worldOffset-base+33)/(chunkLength*chunks.length))*chunkLength*chunks.length;}
for(let i=0;i<structures.length;i++){const base=i*12-36;structures[i].position.x=base+Math.floor((worldOffset-base+36)/(12*structures.length))*12*structures.length;}
for(let i=obstacles.length-1;i>=0;i--){let o=obstacles[i];o.group.position.x=o.x+droneX();if(o.kind==='bat'){o.group.position.y=o.y;const model=o.group.children[0],flap=Math.sin(time*11+o.phase);model.rotation.z=Math.sin(time*2+o.phase)*.07;model.userData.wings.forEach(w=>{w.rotation.z=flap*.28*w.userData.side;w.rotation.y=(.10+Math.sin(time*11+o.phase-.45)*.17)*w.userData.side;});}if(o.x<state.distance-24){disposeObject(o.group);obstacles.splice(i,1);}}
if(mode==='intro'){drone.position.set(aspect<.8?0:4,-1+Math.sin(time*.8)*.16,2);drone.scale.setScalar(aspect<.8?1.7:1.9);drone.rotation.set(.19,Math.sin(time*.14)*.13-.15,.035+Math.sin(time*.9)*.015);spot.intensity=280;beamMat.uniforms.opacity.value=.085;}else{drone.scale.lerp(new T.Vector3(1,1,1),dt*5);drone.position.set(droneX(),state.y,1);let tilt=state.mode==='playing'?-state.vy*.045:state.landed?-.27:Math.sin(state.crashTime*3)*.4;drone.rotation.z=T.MathUtils.lerp(drone.rotation.z,tilt,dt*7);drone.rotation.x=T.MathUtils.lerp(drone.rotation.x,.14,dt*5);drone.rotation.y=T.MathUtils.lerp(drone.rotation.y,-.08,dt*4);if(state.mode==='playing'){spot.intensity=240;beamMat.uniforms.opacity.value=.08;}drone.visible=!(state.mode==='playing'&&state.invulnerable>0&&state.hits>0&&Math.floor(time*12)%2===0);}
updateLidar();navLights.forEach((g,i)=>{g.material.opacity=(state.mode==='playing'||mode==='intro')?.72+Math.sin(time*3+i)*.15:.16;});bounce.intensity=(state.mode==='playing'||mode==='intro')?28:state.landed?1:4;halo.intensity=(state.mode==='playing'||mode==='intro')?18:3;
const active=state.mode==='playing'||mode==='intro';rotors.forEach((r,i)=>r.rotation.y+=dt*(active?(held?90:65):Math.max(0,65-state.crashTime*42))*(i%2?1:-1));
if(audio){const flying=mode==='playing'&&state.mode==='playing',power=held||time<tapUntil,target=flying?(power?260:195):70,now=audio.ctx.currentTime;audio.motors.forEach(({blade,whine},i)=>{blade.frequency.setTargetAtTime(target+i*3.7,now,.17);whine.frequency.setTargetAtTime(target*5.6+i*17,now,.22);});audio.pulse.frequency.setTargetAtTime(target*.5,now,.2);audio.airGain.gain.setTargetAtTime(power?.30:.20,now,.2);audio.airFilter.frequency.setTargetAtTime(power?2100:1550,now,.2);audio.gain.gain.setTargetAtTime(flying?.3:0,now,.35);}

for(let i=0;i<dustCount;i++){dustPos[i*3]-=dt*(mode==='playing'&&state.mode==='playing'?1.2:.12);if(dustPos[i*3]<-24)dustPos[i*3]=25;}dustG.attributes.position.needsUpdate=true;dustM.uniforms.dronePos.value.copy(drone.position);dustM.uniforms.clock.value=time;
for(let i=particles.length-1;i>=0;i--){let p=particles[i];p.age+=dt;p.m.position.x+=p.vx*dt;p.m.position.y+=p.vy*dt;if(!p.smoke)p.vy-=dt*5;p.m.material.opacity=(1-p.age/p.life)*(p.smoke?.42:1);p.m.scale.setScalar(p.size*(p.smoke?1+p.age*2:1));if(p.age>p.life){scene.remove(p.m);p.m.material.dispose();particles.splice(i,1);}}
shake=Math.max(0,shake-dt);camera.position.x=shake?(Math.random()-.5)*shake*.65:0;camera.position.y=1.1+(shake?(Math.random()-.5)*shake*.65:0);renderer.render(scene,camera);}
requestAnimationFrame(animate);
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'get_flight_status',description:'Read the current drone flight, distance, score and remaining lives.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({status:mode==='intro'?'intro':paused?'paused':state.mode,distance:Math.floor(state.distance),score:Math.floor(state.distance),lives:state.lives})})).catch(()=>{});}catch(e){}}
